apiVersion: v1
kind: Service
metadata:
  name: service-projectapp-backend
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    name: projectapp-backend