apiVersion: v1
kind: Service
metadata:
  name: service-projectapp-frontend
spec:
  ports:
    - port: 80
      nodePort: 30001
      targetPort: http
      protocol: TCP
      name: http
  type: NodePort
  # type: LoadBalancer
  selector:
    name: projectapp-frontend